title: CSS Advanced
email: zkzhelyazkov@gmail.com
description: Vse Taia
destination: docs
baseurl: "/su-jekyll-zsite"
url: ""
twitter_username: zhivko
github_username:  ZhivkoZhelyazkov

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs

# navigation:
#   - url: /home/
#     text: Home
#   - url: /about/
#     text: About
#   - url: /services/
#     text: Services
#     items:
#       - url: /service_1/
#         text: Service_1
#       - url: /service_2/
#         text: Service_2
#       - url: /service_3/
#         text: Service_3
#       - url: /service_4/
#         text: Service_4
#   - url: /contacts/
#     text: Contacts